export const OPTIONS = {
  STACKS: [
    {value: "javascript", title: "Javascript"},
    {value: "typescript", title: "Typescript"},
    {value: "react", title: "React"},
    {value: "vue", title: "Vue"},
    {value: "node.js", title: "Node.js"},
    {value: "spring", title: "Spring"},
    {value: "java", title: "Java"},
    {value: "next.js", title: "Next.js"},
    {value: "express", title: "Express"},
    {value: "go", title: "Go"},
    {value: "c", title: "C"},
    {value: "python", title: "Python"},
    {value: "django", title: "Django"},
    {value: "swift", title: "Swift"},
    {value: "kotlin", title: "Kotlin"},
    {value: "mysql", title: "MySQL"},
    {value: "mongodb", title: "MongoDB"},
    {value: "php", title: "php"},
    {value: "graphql", title: "GraphQL"},
    {value: "reactnative", title: "ReactNative"},
    {value: "firebase", title: "Firebase"},
    {value: "unity", title: "Unity"},
    {value: "flutter", title: "Flutter"},
    {value: "aws", title: "AWS"},
    {value: "kubernetes", title: "Kubernetes"},
    {value: "docker", title: "Docker"},
    {value: "git", title: "Git"},
    {value: "figma", title: "Figma"},
    {value: "zeplin", title: "Zeplin"},
  ],
};
